sources:
  - name: Authors
    handler:
      graphql:
        endpoint: http://localhost:4100/graphql
      transforms:
        - typeMerging:
            queryFields:
              - queryFieldName: author
                keyField: id
              - queryFieldName: book
                keyField: id
  - name: Books
    handler:
      graphql:
        endpoint: http://localhost:4200/graphql
    transforms:
      - typeMerging:
          queryFields:
            - queryFieldName: book
              keyField: id
            - queryFieldName: author
              keyField: id

#additionalResolvers:
#  # Create a stitching resolver with batching
#  # to solve N+1 problem
#  - sourceName: Authors
#    sourceTypeName: Query
#    sourceFieldName: author
#    requiredSelectionSet: "{ id }"
#    keyField: id
#    keysArg: ids
#    targetTypeName: Book
#    targetFieldName: author

serve:
  port: 5000
  cors: { origin: http://localhost:4000 }
  playground: true
  browser: false
